In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
# 여기서 중괄호 {}는 format() 함수의 인자가 치환되어 들어갈 자리를 지정하고 있다. 콜론(:)을 기준으로 왼쪽은 인덱스(순서), 오른쪽은 형식 지정자이다.
# ndim은 Numpy의 ndarray 객체가 가진 속성으로 해당 배열의 축(Axis)의 개수를 반환한다.
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [4]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [5]:
# int와 unsigned int의 차이는 무엇인가?
# int는 양수의 정수, 음수의 정수 모두 가능하나, unsigned int는 양수의 정수만 허용한다.
# int는 MSB(최상위 비트, 부호 비트)로 양수 또는 음수를 표현해야 하나, unsigned int는 양수만 가능하기 때문에 모든 비트를 숫자 크기로 표현할 수 있어, 양수 표현 범위가 2배가 된다.

list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [6]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [7]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [8]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [9]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
arrayl = np.arange(10)
print(array1)
array2 = arrayl.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = arrayl.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [13]:
array0 = np.arange(8)
array3d = array0.reshape(2, 2, 2)
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array0.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [17]:
array1 = np.arange(start=1, stop=10)
print(array1)
# index는 0부터 시작, array1[2]는 3번째
value = array1[2]
print('value:', value)
print('value type:', type(value))


[1 2 3 4 5 6 7 8 9]
value: 3
value type: <class 'numpy.int64'>


In [19]:
print('맨 뒤는', array1[-1], '그 다음 뒤는', array1[-2])

맨 뒤는 9 그 다음 뒤는 8


In [20]:
array1[0] = 9
array1[1] = 8
array1

array([9, 8, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array1_1d = np.arange(start=1, stop=10)
array1_2d = array1_1d.reshape(-1, 3)
print(array1_2d)
# 순서는 (행, 열)이라는 것을 명심하자!
print('(row=0, col=0):', array1_2d[0, 0])
print('(row=0, col=2):', array1_2d[0, 2])
print('(row=1, col=2):', array1_2d[1, 2])
print('(row=2, col=0):', array1_2d[2, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0): 1
(row=0, col=2): 3
(row=1, col=2): 6
(row=2, col=0): 7


In [ ]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))
# 슬라이싱한다고 ndarray가 list가 되지는 않는다.

[1 2 3]
<class 'numpy.ndarray'>


In [26]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
# 처음부터 인덱스 2
print(array4)

array5 = array1[2:]
# 인덱스 2부터 끝까지
print(array5)

array6 = array1[:]
# 모두
print(array6)

[1 2 3]
[3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [35]:
print('여기를 참고해주세요:\n', array1_2d)
print('\n')
print('0:2, 0:2:\n', array1_2d[0:2, 0:2])
print('1:3, 1:3:\n', array1_2d[1:3, 1:3])
print(':, :\n', array1_2d[:, :])
print(':2, 1:\n', array1_2d[:2, 1])


여기를 참고해주세요:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


0:2, 0:2:
 [[1 2]
 [4 5]]
1:3, 1:3:
 [[5 6]
 [8 9]]
:, :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
:2, 1:
 [2 5]


In [36]:
print(array1_2d[0])
print(array1_2d[1])
print('array1_2d[0] shape:', array1_2d[0].shape)

[1 2 3]
[4 5 6]
array1_2d[0] shape: (3,)


In [42]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(-1, 3)
print(array2d)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =', array3.tolist())

array4 = array2d[[0, 1], 0:2]
# ((0,0), (0,1)), ((1,0), (1,1))
print('array2d[[0, 1], 0:2] =', array4.tolist())

array5 = array2d[[0, 1]]
# ((0, :), (1, :))
print('array2d[[0, 1]] =', array5.tolist())



[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0, 1], 2] = [3, 6]
array2d[[0, 1], 0:2] = [[1, 2], [4, 5]]
array2d[[0, 1]] = [[1, 2, 3], [4, 5, 6]]


In [43]:
# 불린 인덱싱의 장점은 [] 안에 array1d > 5 Boolean indexing을 바로 적용 가능하다는 것이다.
array3 = array1d[array1d>5]
print(array3)

[6 7 8 9]


In [44]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_index = np.array([False, False, False, False, False,  True,  True,  True, True])
array3 = array1d[boolean_index]
array3
# 1. 대괄호 안에 조건식을 바로 넣기
# 2. 별도로 boolean index를 생성해서 넣기
# 3. 직접 index를 만들어서 넣기

array([6, 7, 8, 9])

In [52]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)
# np.sort()로 정렬해보자.
sort_array1 = np.sort(org_array)
print('np.sort() 정렬 후:', sort_array1)
print('원본은:', org_array)
# ndarray.sort()로 정렬하면?
sort_array2 = org_array.sort()
print('반환된 행렬:', sort_array2)
print('그리고 원본은:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 정렬 후: [1 3 5 9]
원본은: [3 1 9 5]
반환된 행렬: None
그리고 원본은: [1 3 5 9]


In [53]:
array2d = np.array([[8, 12],
                   [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼:\n', sort_array2d_axis1)

로우:
 [[ 7  1]
 [ 8 12]]
칼럼:
 [[ 8 12]
 [ 1  7]]


In [55]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(sort_indices)

[1 0 3 2]


In [78]:
name_array = np.array(['존', '마이크', '사라', '케이트', '사무엘'])
score_array = np.random.randint(70, 101, size=5)
print(score_array)

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 socre_array의 index:', sort_indices_asc)
print('ranking:', name_array[sort_indices_asc])



[73 97 76 76 91]
성적 오름차순 정렬 시 socre_array의 index: [0 2 3 4 1]
ranking: ['존' '사라' '케이트' '사무엘' '마이크']


In [80]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('내적 결과:\n', dot_product)

내적 결과:
 [[ 58  64]
 [139 154]]


In [81]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]
