In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
wine = pd.read_csv('https://bit.ly/wine_csv_data')
data = wine.drop('class', axis=1)
target = wine['class']
train_input, test_input, train_target, test_target = train_test_split(data, target, random_state=42, test_size=0.2)


In [3]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(rf, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))
# 과대적합 발생!

0.9973541965122431 0.8905151032797809


In [4]:
rf.fit(train_input, train_target)
rf.feature_importances_
# sugar 의 중요도가 감소하였다. 그러나 여전히 1순위.

array([0.23167441, 0.50039841, 0.26792718])

In [5]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
rf.oob_score_
# OOB 점수로 교차 검증을 대신할 수 있고, 결과적으로 훈련 세트에 더 많은 샘플을 사용할 수 있다.

0.8934000384837406

In [6]:
# 엑스트라 트리: 부트스트랩 샘플을 사용하지 않는다. 
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9974503966084433 0.8887848893166506


In [7]:
et.fit(train_input, train_target)
et.feature_importances_

array([0.20183568, 0.52242907, 0.27573525])

In [8]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9464595437171814 0.8780082549788999


In [9]:
gb.fit(train_input, train_target)
gb.feature_importances_

array([0.15882696, 0.6799705 , 0.16120254])

In [10]:
from sklearn.ensemble import HistGradientBoostingClassifier
hgb = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgb, train_input, train_target, return_train_score=True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9321723946453317 0.8801241948619236


In [13]:
from sklearn.inspection import permutation_importance
hgb.fit(train_input, train_target)
results = permutation_importance(hgb, train_input, train_target, n_repeats=10, random_state=42, n_jobs=-1)
results['importances_mean']

array([0.08876275, 0.23438522, 0.08027708])

In [18]:
!pip install xgboost
from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method='hist', random_state=42)
scores = cross_validate(xgb, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']))

0.9567059184812372


In [19]:
!pip install lightgbm

   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 9.8 MB/s  0:00:00


In [20]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(random_state=42)
scores = cross_validate(lgb, train_input, train_target, n_jobs=-1, return_train_score=True)
print(np.mean(scores['train_score']))

0.935828414851749
